-- -- password test user - password124
-- INSERT INTO users (id, username, email, password)
-- VALUES (1, 'test', 'test@mail.io', '$2a$10$F3qtmKT/rKl/bvP5MhVge.1lFyvYec4AZag8BMOLjDlciahEn5TAO');
--
-- INSERT INTO user_role (user_id, roles)
-- VALUES (1, 'ROLE_USER');